backend:
  name: git-gateway
  branch: main

media_folder: "berita"
public_folder: "/berita"

collections:
  - name: "berita"
    label: "Berita"
    folder: "berita"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
      - { label: "Gambar", name: "image", widget: "image" }
